version: "3.7"

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "8080:8080"
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
